---
title: "Nonlinear Models"
author: "Nakul Camasamudram"
date: "11/18/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Generalized Additive Models
===============================

```{r}
# Imports

library(mgcv)
library(tidyr)
library(dplyr)
library(ggplot2)
library(visreg)
library(leaps)
```

## Load Data

```{r}
set.seed(123)

## Read data

# Original data
boston <- read.csv("./data/boston_undummied.csv", sep = ",", header=TRUE, na.strings=c("", " ", "NA"))

# Neighbourhood -> Distance to airport and downtown
boston.dboth <- read.csv("./data/boston_dboth_undummied.csv", sep = ",", header=TRUE, na.strings=c("", " ", "NA"))
boston.dboth <- boston.dboth %>% select(-airport, -downtown)


# Neighbourhood -> Distance to airport
boston.dairport <- read.csv("./data/boston_dairport_undummied.csv", sep = ",", header=TRUE, na.strings=c("", " ", "NA"))
boston.dairport <- boston.dairport %>% select(-airport, -downtown)

# Neighbourhood -> Distance to downtown
boston.ddowntown <- read.csv("./data/boston_ddowntown_undummied.csv", sep = ",", header=TRUE, na.strings=c("", " ", "NA"))
boston.ddowntown <- boston.ddowntown %>% select(-airport, -downtown)
```

```{r}
# Make train, test and validation sets
data_split <- function(df) {
  # Train
  train_ind <- sample(1:nrow(df), 0.6*nrow(df))
  train_df <- df[train_ind, ]
  
  # Test + Validation
  test_valid_df <- df[-train_ind, ]
  test_ind <- sample(1:nrow(test_valid_df), 0.5*nrow(test_valid_df))
  test_df <- test_valid_df[test_ind, ]
  valid_df <- test_valid_df[-test_ind, ]
  return(list(train=train_df, test=test_df, valid=valid_df))
}

# Split into train, test and validation data

# original
split <- data_split(boston)
boston.train <- split$train
boston.test <- split$test
boston.valid <- split$valid


# distance to airport and downtown
split <- data_split(boston.dboth)
boston.dboth.train <- split$train
boston.dboth.test <- split$test
boston.dboth.valid <- split$valid


# distance to airport
split <- data_split(boston.dboth)
boston.dairport.train <- split$train
boston.dairport.test <- split$test
boston.dairport.valid <- split$valid


# distance to downtown
split <- data_split(boston.dboth)
boston.ddowntown.train <- split$train
boston.ddowntown.test <- split$test
boston.ddowntown.valid <- split$valid
```

### EDA

```{r, warning=FALSE}
continuous_features <- c("bedrooms", "guests_included", "beds", "bathrooms", "minimum_nights", "accommodates", "number_of_reviews", "ddowntown", "dairport", "price")

dmelt <- gather(select(boston.dboth, continuous_features), key=Variable, value=Value, -price)

scatterwrap <- ggplot(aes(x=Value,y=price), data=dmelt) +
  geom_point(color='#FF5503',alpha=.75) +
  geom_smooth(se=F) + 
  facet_wrap(~Variable, scales='free_x') +
  labs(x='')

scatterwrap
```

## Build Models

## Explore variable selection using linear models

```{r}
# Regular subset selection
reg1 <- regsubsets(price~., data = boston.dboth.train, really.big = T)
reg1.summary <- summary(reg1)

par(mfrow = c(2,2))
plot(reg1.summary$rss, xlab = "Number of variables", ylab = "Residual Sum of Squares (RSS)", type = "l")
plot(reg1.summary$adjr2, xlab = "Number of variables", ylab = "Adjacent R square", type = "l")
plot(reg1.summary$cp, xlab = "Number of variables", ylab = "CP", type = "l")
plot(reg1.summary$bic, xlab = "Number of variables", ylab = "BIC", type = "l")

which.min(reg1.summary$bic)
# Results: host_identity_verified, property_type, room_type, bathrooms, bedrooms, guests_included, ddowntown, dairport
```

```{r}
null <- lm(price~1, data=boston.dboth.train)
full <- lm(price~., data=boston.dboth.train)

forward_selection <- step(null, scope=list(lower=null, upper=full), direction="forward")
# Results: price ~ accommodates + ddowntown + bathrooms + room_type + property_type + bedrooms + dairport + host_identity_verified + instant_bookable + guests_included + cancellation_policy + beds + number_of_reviews

# The same predictors were got when "backward" and "both" directions for steps selctions as well.
```


### GAM based on the variable selection methods above

```{r}
# Variables selected from subset selection
gam4 <- gam(price ~ host_identity_verified + property_type + room_type + s(bathrooms) + s(bedrooms, k=5) + s(guests_included) + s(ddowntown) + s(dairport), data=boston.dboth.train)
summary(gam4)
# GCV = 13343, Deviance Explained = 48.5%
```

```{r}
# Variables selected from forward selection
gam5 <- gam(price ~ s(accommodates) + s(ddowntown) + s(bathrooms) + room_type + property_type + s(bedrooms, k=5) + s(dairport) + host_identity_verified + instant_bookable + s(guests_included) + cancellation_policy + s(beds) + s(number_of_reviews), data=boston.dboth.train)
summary(gam5)
# GCV = 13193, Deviance explained = 49.6%
```

### Variable selection within GAM

```{r}
gam6 <- gam(price ~ host_is_superhost + host_identity_verified + property_type + room_type + s(accommodates) + s(bathrooms) + s(bedrooms, k=5) + s(beds) + bed_type + s(guests_included) + s(minimum_nights) + s(number_of_reviews) + instant_bookable + is_business_travel_ready + cancellation_policy + s(ddowntown) + s(dairport), data=boston.dboth.train, select=T, method="REML")
summary(gam6)
# Deviance exlained = 49.8%
```

```{r}
gam7 <- gam(price ~ host_identity_verified + property_type + room_type + instant_bookable + s(accommodates) + s(bathrooms) + s(bedrooms, k=5) + s(beds) + s(guests_included) + s(minimum_nights) + s(number_of_reviews) + s(ddowntown) + s(dairport), data=boston.dboth.train, select=T, method="REML")
summary(gam7)
# Deviance exlained = 49.7%
```

```{r}
# Model comparison
anova(gam4, gam5, gam6, gam7, test="Chisq")
# Model 5 is the best accoording to Chisq
```


### Model comparison on test data

```{r}
rmspe <- function(test_data, model) {
  return(sqrt(mean((test_data$price - predict.gam(model, test_data)) ^ 2)))
}

gam4.rmspe <- rmspe(boston.dboth.test, gam4)
gam5.rmspe <- rmspe(boston.dboth.test, gam5)
gam6.rmspe <- rmspe(boston.dboth.test, gam6)
gam7.rmspe <- rmspe(boston.dboth.test, gam7)
gam4.rmspe # 141.8996
gam5.rmspe # 146.0915
gam6.rmspe # 144.1888
gam7.rmspe # 144.2769
which.min(c(gam4.rmspe, gam5.rmspe, gam6.rmspe, gam7.rmspe))
```


### Other models (variable selection within GAMs)

#### Original
```{r}
gam8 <- gam(price ~ host_is_superhost + host_identity_verified + neighborhood + property_type + room_type + s(accommodates) + s(bathrooms) + s(bedrooms, k=5) + s(beds) + bed_type + s(guests_included) + s(minimum_nights) + s(number_of_reviews) + instant_bookable + is_business_travel_ready + cancellation_policy, data=boston.train, select=T, method="REML")
summary(gam8)
# Deviance exlained = 45%

gam8.rmspe <- rmspe(boston, gam8)
gam8.rmspe # 123.9392
```

#### Distance to airport
```{r}
gam9 <- gam(price ~ host_is_superhost + host_identity_verified + property_type + room_type + s(accommodates) + s(bathrooms) + s(bedrooms, k=5) + s(beds) + bed_type + s(guests_included) + s(minimum_nights) + s(number_of_reviews) + instant_bookable + is_business_travel_ready + cancellation_policy + s(dairport), data=boston.dairport, select=T, method="REML")
summary(gam9)
# Deviance exlained = 40.9%

gam9.rmspe <- rmspe(boston.diaport, gam9)
gam9.rmspe # 123.9392
```

#### Distance to downtown
```{r}
gam10 <- gam(price ~ host_is_superhost + host_identity_verified + property_type + room_type + s(accommodates) + s(bathrooms) + s(bedrooms, k=5) + s(beds) + bed_type + s(guests_included) + s(minimum_nights) + s(number_of_reviews) + instant_bookable + is_business_travel_ready + cancellation_policy + s(ddowntown), data=boston.ddowntown, select=T, method="REML")
summary(gam10)
# Deviance exlained = 40.6%

gam10.rmspe <- rmspe(boston.ddowntown, gam10)
gam10.rmspe # 124.26
```
